import { Clock } from 'lucide-react';

interface UpdateEntry {
  date: string;
  items: string[];
}

const updates: UpdateEntry[] = [
  {
    date: 'February 22, 2025',
    items: [
      'Added My Content — save, browse, and revisit content drafts generated by the Content Generator with full original instructions preserved',
      'Added Event Navigator — AI-powered event recommendation engine with tier scoring, competitor analysis, strategic briefs, and saved event plans',
      'Added My Event Plans — view and manage saved event lineup plans from the Event Navigator',
    ],
  },
];

export default function UpdatesPage() {
  return (
    <div className="p-4 md:p-6 max-w-3xl mx-auto">
      <div className="mb-6">
        <h1 className="text-xl font-bold text-dd-slate">Updates</h1>
        <p className="text-sm text-dd-gray mt-1">
          A log of changes and new features added to the Campaign Command Center
        </p>
      </div>

      <div className="space-y-6">
        {updates.map((entry) => (
          <div key={entry.date} className="bg-white rounded-xl border border-dd-border p-5">
            <div className="flex items-center gap-2 mb-3">
              <Clock size={16} className="text-dd-teal" />
              <h2 className="text-sm font-semibold text-dd-slate">{entry.date}</h2>
            </div>
            <ul className="space-y-2">
              {entry.items.map((item, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-dd-slate">
                  <span className="text-dd-teal mt-1.5 shrink-0">&#8226;</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
}
